# Netlify configuration for Chronocap frontend
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  # Set VITE_API_BASE in the Netlify UI (Site settings > Build & deploy > Environment) for production API endpoint.

# History API fallback for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
